# Mask kind. Choose between mixed, full, etc.
masks:
  kind: mixed
  invert_proba: 0.5
  irregular_proba: 0.16
  box_proba: 0.5
  full_proba: 0.16
  segm_proba: 0.18
  box_kwargs:
    margin: 10
    bbox_min_size: 30
    bbox_max_size: 100
    min_times: 1
    max_times: 3

# The probability of applying the augmentation.
augs:
  identity:       1
  jpeg:           1
  resize:         1
  crop:           1
  rotate:         1
  hflip:          1
  perspective:    1
  gaussian_blur:  1
  median_filter:  1
  brightness:     1
  contrast:       1
  saturation:     1
  hue:            1
  crop_resize_pad: 2

augs_params:
  resize:
    min_size: 0.7
    max_size: 1.5
  crop:
    min_size: 0.33
    max_size: 1.0
  rotate:
    min_angle: -10
    max_angle: 10
  perspective:
    min_distortion_scale: 0.1
    max_distortion_scale: 0.5
  jpeg:
    min_quality: 40
    max_quality: 80
  gaussian_blur:
    # sigma = 0.3 * ((kernel_size - 1) * 0.5 - 1) + 0.8
    min_kernel_size: 3
    max_kernel_size: 17
  median_filter:
    min_kernel_size: 3
    max_kernel_size: 7
  brightness:
    min_factor: 0.5
    max_factor: 2
  contrast:
    min_factor: 0.5
    max_factor: 2.0
  saturation:
    min_factor: 0.5
    max_factor: 2
  hue:
    min_factor: -0.1
    max_factor: 0.1
  crop_resize_pad:
    'resize_min': 0.7
    'resize_max': 1.5
    'crop_min': 0.5
    'crop_max': 0.66