model: sam_base

sam_tiny:
  encoder:
    img_size: 256
    embed_dim: 192
    out_chans: 192
    depth: 12
    num_heads: 3
    patch_size: 16
    global_attn_indexes: [2, 5, 8, 11]
    window_size: 8
    mlp_ratio: 4
    qkv_bias: True
    use_rel_pos: True
  pixel_decoder:
    upscale_stages: [4, 2, 2]  # 4*2*2 = x16 (patch size)
    embed_dim: 192  # = encoder.out_chans
    nbits: 16
    sigmoid_output: False
    upscale_type: 'bilinear'  # 'pixelshuffle', 'nearest', 'conv',  'bilinear'

sam_small:
  encoder:
    img_size: 256
    embed_dim: 384
    out_chans: 384
    depth: 12
    num_heads: 6
    patch_size: 16
    global_attn_indexes: [2, 5, 8, 11]
    window_size: 8
    mlp_ratio: 4
    qkv_bias: True
    use_rel_pos: True
  pixel_decoder:
    upscale_stages: [4, 2, 2]  # 4*2*2 = x16 (patch size)
    embed_dim: 384  # = encoder.out_chans
    nbits: 16
    sigmoid_output: False
    upscale_type: 'bilinear'  # 'pixelshuffle', 'nearest', 'conv',  'bilinear'

sam_base:
  encoder:
    img_size: 256
    embed_dim: 768
    out_chans: 768
    depth: 12
    num_heads: 12
    patch_size: 16
    global_attn_indexes: [2, 5, 8, 11]
    window_size: 8
    mlp_ratio: 4
    qkv_bias: True
    use_rel_pos: True
  pixel_decoder:
    upscale_stages: [4, 2, 2]  # 4*2*2 = x16 (patch size)
    embed_dim: 768  # = encoder.out_chans
    nbits: 16
    sigmoid_output: False
    upscale_type: 'bilinear'  # 'pixelshuffle', 'nearest', 'conv',  'bilinear'
